### PR TITLE
Changes values for language spanish

### PR DESCRIPTION
**Pull request by chernandezq**

### CODE REVIEW

**Comment by chernandezq** [comment]
Thanks, now How I can put the spanish message ?

**Comment by hameno** [comment]
What do you mean?

**Comment by chernandezq** [comment]
When you leave the error, display the text in Spanish

**Comment by hameno** [comment]
Still no idea what you mean...

**Comment by chernandezq** [comment]
The message now when called .validate appears in English, as I do for this same message appears in Spanish.

**Comment by hameno** [comment]
You need to use the correct version. This change has not yet been released so you need to include the development version.

**Pull request merged**
